### ISSUE TITLE
internal.py Ag Grid Image Image Column

### ISSUE THREAD

**Issue by ElangoSubramani** [Coding-with-Adam/response-reporting-dashboard#4] opened 2024-04-05 16:34 UTC
- The problem is while adding a new row the uploaded image paths vanishes but the images are stored in the server but the images are in the server. 

- The photos are uploaded to the dash server inside the assets/uploaded_images folder. The path of the image directory is updated in the data frame. I have created a separate branch in the repo branch named "internal_page ". You can find the code there. I  have written the JS functions to alter the ag Grid.

- commit messages: [https://github.com/Coding-with-Adam/response-reporting-dashboard/commits/Internal_Page/]

**Comment by Coding-with-Adam** [comment] 2024-04-07 19:48
> The problem is while adding a new row the uploaded image paths vanishes but the images are stored in the server but the images are in the server.


Hi @ElangoSubramani 
It's not exactly clear to me what the problem is. Can you please rephrase.

I tried running the code in your branch. First we have to fix the issue of misalignment between column fields in your internal.py file. The field name in the `cols` list on line 15 are different then the field names when one clicks the add-row button on line 165.

```
    elif ctx.triggered_id == "add-row-btn" and data:
        new_row = [{
            "Timestamp": "",
            "Reporting User": "",
            "Platform": "",
            "URL link": "",
            "Report Type": "",
            "Answer Date": "",
            "Platform Decision": "",
            "Policy": "",
            "Appeal": ""
        }]
```

Whenever one uploads a new image, the script creates a new `pages` folder inside the original pages folder. Can you please change that so we don't have a duplicate of the `pages` folder.

**Comment by Coding-with-Adam** [comment] 2024-04-10 12:21
Closing this commit for now because we made some progress with image upload on another branch. 
Feel free to reopen this issue, @ElangoSubramani if you'd like to continue working on it.

**Closed as completed by Coding-with-Adam** 2024-04-10 12:21 UTC
